name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if your default branch is named that

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # change if your files are in a subdirectory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
